# Generated by Django 2.1.2 on 2018-12-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hethong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
